### ISSUE TITLE
Callback parameter for setLanguage()

### ISSUE THREAD

**Issue by paulguz** [fabi1cazenave/webL10n#56]
I'm using setLanguage() in my unit tests to ensure my localisation is functioning.

Now that resources are loaded asynchronously, you must wait for setLanguage() to complete before continuing.  

I've made it work using the 'localized' event, but I don't find that intuitive - I would expect 'localized' to fire after translation, not just loading a language.

If there were a callback parameter to setLanguage, it wouldn't be so ambiguous.

Paul

**Comment by Rob--W** [comment]
Could you try out #57 and see if it resolves your issue?

**Comment by paulguz** [comment]
Yeah, that seems to work.  Many thanks.
