### ISSUE TITLE
call variable

### ISSUE THREAD

**Issue by bluetch** [fabi1cazenave/webL10n#58]
Excuse me,
I am a beginner for JS.
Is possible to load variable in other script with webL10n?

ex:
var myLanguage = getLanguage();

thank you.

**Comment by Rob--W** [comment]
The code snippet that you've given does indeed assign the return value of some method to a variable, but I guess that you're looking for something else. What's the problem you're trying to solve?

**Comment by bluetch** [comment]
thank for your reply.

I would like to do some UI change via language.
ex: 
language=zn-cn, show 3 div with google map
language=en-us, show 5 div width video
so I need var language variable to change my web content.

**Comment by Rob--W** [comment]
```
var language = document.webL10n.getLanguage();
```

Or, without this library:

```
var language = navigator.language || navigator.userLanguage;
```

**Comment by bluetch** [comment]
I tried, but didn't get anything.

var language = document.webL10n.getLanguage();
console.log(language);

and I get another bug ..below

![l10n](https://cloud.githubusercontent.com/assets/4100698/6439715/79527994-c110-11e4-9563-179fc6ec1b67.png)

**Comment by Rob--W** [comment]
Could you get the latest version of l10n.js? It includes several fixes, including a solution to that synchronous XMLHttpRequest warning.

**Comment by bluetch** [comment]
I have just updated l10n.js, it fix synchronous XMLHttpRequest warning~
but my variable still unavailable.

![2015-03-02 19 29 05](https://cloud.githubusercontent.com/assets/4100698/6439899/9088594c-c112-11e4-911c-b6a143a7285b.png)

**Comment by Rob--W** [comment]
`getLanguage` only returns something useful *after* [loadLocale](https://github.com/fabi1cazenave/webL10n/blob/master/l10n.js#L304) has been invoked. This happens after DOMContentLoaded.

Add an event listener for the "localized" event, and you will get a correct value.

Or, if you are only interested in the user's locale, use the snippet at the end of my first reply.

**Comment by bluetch** [comment]
Got it, thank u :)
